### ISSUE TITLE
Add Auto-Update skills.csv On Program Launch

### ISSUE THREAD

**Issue by ryanelian** [TyroneSama/OverParse#1]
Download data from [https://github.com/VariantXYZ/PSO2ACT/raw/master/PSO2ACT/skills.csv](https://github.com/VariantXYZ/PSO2ACT/raw/master/PSO2ACT/skills.csv)

To avoid the chore of manual updating skills.csv every single time!

**Comment by TyroneSama** [comment]
The skills.csv that's included with OverParse should be more complete than the version in PSO2ACT (though once the current set of IDs is organized and verified, I'll send Variant a pull request so he can get his up-to-date).

As a user, you shouldn't need to update anything, unless I completely misunderstand your meaning.

**Comment by ryanelian** [comment]
Ah I thought their version is more complete. Then probably the auto-update should pull from [https://github.com/TyroneSama/OverParse/raw/master/OverParse/skills.csv](https://github.com/TyroneSama/OverParse/raw/master/OverParse/skills.csv) instead.

Nah I don't mean as a user. Currently if you are to make small changes in the skills.csv, you will need to redeploy everything and that's not good for your soul. Perhaps by making an auto-update mechanism, you will save yourself that trouble?

**Comment by ryanelian** [comment]
Or better yet, if you can make so that https://www.appveyor.com/ CI automatically compiles your application, your can make a self-updating and self-versioning app.

**Comment by TyroneSama** [comment]
It's on the table, but at the moment I'm redeploying everything every 2 seconds anyway, so it's not a high priority right now. Maybe I ought to have OverParse checking for new releases, instead of new versions of skills.csv? I'll probably do _something,_ at any rate. I appreciate your concern for my health, though. :')

I'll look into Appveyor, but it kinda seems like overkill for a project of this scope.
